export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const FETCH_LANDMARKS_PENDING = 'FETCH_LANDMARKS_PENDING';
export const FETCH_LANDMARKS_SUCCESS = 'FETCH_LANDMARKS_SUCCESS';
export const FETCH_LANDMARKS_FAILED = 'FETCH_LANDMARKS_FAILED';
